name: Deploy DineTech to Azure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AZURE_WEBAPP_NAME_BACKEND: dine-tech-backend
  AZURE_WEBAPP_NAME_FRONTEND: dine-tech-frontend
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    # Build Frontend
    - name: 'Install Frontend Dependencies'
      run: |
        cd frontend
        npm install --legacy-peer-deps

    - name: 'Build Frontend'
      run: |
        cd frontend
        npm run build

    # Build Backend
    - name: 'Install Backend Dependencies'
      run: |
        cd backend
        npm install

    # Deploy Backend to Azure
    - name: 'Deploy Backend to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: './backend'

    # Deploy Frontend to Azure
    - name: 'Deploy Frontend to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: './frontend/dist'